// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0rIrSLJ8jaAo5JdNKN_8W-lMMWTRZU3A',
    appId: '1:910161527656:android:261de34f1150ca6b0eccdd',
    messagingSenderId: '910161527656',
    projectId: 'login-firebase-a4a53',
    storageBucket: 'login-firebase-a4a53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJIspnS-I0jRx_FxGVnqcQGqj8jAPBfnY',
    appId: '1:910161527656:ios:ed3fd1488deda0db0eccdd',
    messagingSenderId: '910161527656',
    projectId: 'login-firebase-a4a53',
    storageBucket: 'login-firebase-a4a53.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJIspnS-I0jRx_FxGVnqcQGqj8jAPBfnY',
    appId: '1:910161527656:ios:ed3fd1488deda0db0eccdd',
    messagingSenderId: '910161527656',
    projectId: 'login-firebase-a4a53',
    storageBucket: 'login-firebase-a4a53.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

}